const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
console.log(arr.push(11));
console.log(arr.pop());
console.log(arr.includes(2));
console.log(arr.slice(2, 5));
console.log(arr.splice(2, 5));
console.log(arr.concat([11, 12, 13]));
console.log(arr.join(' '));
console.log(arr.reverse());
console.log(arr.shift());
console.log(arr.unshift(1));
console.log(arr.sort());
console.log(arr.toString());